version: '3.8'


services:
    web_django:
        build: .
        command: bash -c "/wait && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 "
#        python manage.py makemigrations && python manage.py migrate
        ports:
          - 8000:8000
        env_file:
          - .env
        environment:
            - DB_HOST=db
            - WAIT_HOSTS=db:5432
        depends_on:
            -   db
            - redis


    db:
        image: postgres
        ports:
            - '5432:5433'
        environment:
            POSTGRES_DB: 'testovoe'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: '12345'
            POSTGRES_ROOT_PASSWORD: '12345'
            restart: always

        volumes:
            - db_volume:/var/lib/postgresql/data/


    redis:
        image: redis:alpine
        ports:
            -  '6379:6379'
    celery:
        build: .
        command: celery -A djangoProject worker -l info
        volumes:
            - .:/usr/src/app/
        environment:
            - DB_HOST=db
            - DEBUG=1
            - SECRET_KEY=gfaskdhaskjdhaksjhd
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        depends_on:
            - redis
            - db
            - web_django
    celery-beat:
        build: .
        command: celery -A djangoProject beat -l info
        volumes:
            - .:/usr/src/app/
        environment:
            - DB_HOST=db
            - DEBUG=1
            - SECRET_KEY=gfaskdhaskjdhaksjhd
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        depends_on:
            - redis
            - db
            - web_django
volumes:
  db_volume:




