version: '3.8'


services:
    web_django:
        build: .
        command: bash -c "/wait  && python manage.py runserver 0.0.0.0:8000"
        ports:
          - 8000:8000
        env_file:
          - .env
        environment:
            - DB_HOST=db
            - WAIT_HOSTS=postgres:5432
        depends_on:
            -   db

    db:
        image: postgres
        ports:
            - '5433:5433'
        environment:
            POSTGRES_DB: 'django_db'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: '12345'
            POSTGRES_ROOT_PASSWORD: '12345'
            restart: always

        volumes:
            - db_volume:/var/lib/postgresql/data/
volumes:
  db_volume:




