# Generated by Django 4.0.3 on 2022-09-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=20, verbose_name='Заказ №')),
                ('price_usa', models.IntegerField(verbose_name='Стоимость, $')),
                ('deliver_date', models.DateTimeField()),
                ('price_rus', models.FloatField(verbose_name='Стоимость, Р')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
