# Generated by Django 4.0.3 on 2022-09-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='deliver_date',
            field=models.CharField(max_length=30, verbose_name='Дата поставки'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='price_rus',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Стоимость, Р'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='price_usa',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Стоимость, $'),
        ),
    ]
